version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./tts_credentials.json:/app/tts_credentials.json
    restart: unless-stopped